version: 2
jobs:
  qa:
    docker:
    - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Install Python dependencies
        command: |
          pipenv install --dev
    - run:
        name: Run isort
        command: |
          pipenv run isort -c **/*.py
    - run:
        name: Run flake8
        command: |
          pipenv run flake8 zero
    - run:
        name: Install static dependencies
        command: /
          npm i
    - run:
        name: Run eslint
        command: /
          npm run lint
workflows:
  version: 2
  qa-deploy:
    jobs:
    - qa
